POS_Y           .FILL       51
POS_X           .FILL       53
EJ_COL          .FILL       x0000
SPRITE          .FILL       22
                .FILL       22

                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000

                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000

                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1

                .FILL       x7F40
                .FILL       x7F40
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1

                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1


                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1

                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000

                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000

                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000

                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40
                .FILL       x72E1
                .FILL       x72E1

                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       xF000
                .FILL       x7F40
                .FILL       x7F40