__HMR_AND_SCKL          .FILL       22
                        .FILL       22
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
        
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
        
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
        
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
                        .FILL       x72E1
                        .FILL       x72E1
        
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       xF000
                        .FILL       x7F40
                        .FILL       x7F40
