__PADDLE_SPRITE         .FILL   20
                        .FILL   3

                        .FILL   x8000
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x8000

                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F

                        .FILL   x8000
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x001F
                        .FILL   x8000
